stages:
  - build
  - publish

variables:
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

build doc:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t $RELEASE_IMAGE .
    - docker tag $RELEASE_IMAGE "$CI_REGISTRY_IMAGE:latest"
    - docker push $RELEASE_IMAGE
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - /develop|master/
    - tags
  environment: development
  tags:
    - docker

deploy doc:
  image: $RELEASE_IMAGE
  stage: publish
  services:
    - docker:dind
  script:
    - pandoc -s -o fencer-doc.pdf src/**/*.md
    - ./mail/send.sh
  only:
    - tags
  environment: publish
